version: "0.5"
settings:
  tui: false

environment:
  - "ROOT_DIR=${ROOT_DIR:-${PWD}}"
  - "BUILD_DIR=${ROOT_DIR}/.build"
  - "CONTENT_DIR=${BUILD_DIR}/content"
  - "HUGO_DIR=${ROOT_DIR}/.forgejo/hugo"
  - "SCRIPTS_DIR=${ROOT_DIR}/.forgejo/scripts"

processes:
  clone-theme:
    working_dir: "${ROOT_DIR}"
    command: $${SCRIPTS_DIR}/clone-theme.sh ${FRESH:+--fresh}
    availability:
      restart: "no"

  copy-overlay:
    working_dir: "${ROOT_DIR}"
    command: |
      watchexec \
        --debounce 200ms \
        --on-busy-update queue \
        --watch $${HUGO_DIR} \
        -- cp -r $${HUGO_DIR}/. $${BUILD_DIR}/
    depends_on:
      clone-theme:
        condition: process_completed_successfully

  copy-content:
    working_dir: "${ROOT_DIR}"
    command: |
      watchexec \
        --debounce 300ms \
        --ignore '.build/**' \
        --ignore '.forgejo/**' \
        --ignore '.git/**' \
        --on-busy-update queue \
        --watch . \
        -- $${SCRIPTS_DIR}/pre-content.sh
    depends_on:
      clone-theme:
        condition: process_completed_successfully

  hugo-serve:
    working_dir: "${BUILD_DIR}"
    command: |
      hugo serve \
        --buildDrafts \
        --buildExpired \
        --buildFuture \
        --disableFastRender \
        --navigateToChanged \
        --watch
    depends_on:
      copy-overlay:
        condition: process_started
      copy-content:
        condition: process_started
    availability:
      backoff_seconds: 2
      max_restarts: 3
      restart: on_failure
