name: Build and Package

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  BUILD_DIR: ${{ github.workspace }}/.build
  CONTENT_DIR: ${{ github.workspace }}/.build/content
  HUGO_DIR: ${{ github.workspace }}/.forgejo/hugo
  HUGO_VERSION: "0.161.1"
  ROOT_DIR: ${{ github.workspace }}
  SCRIPTS_DIR: ${{ github.workspace }}/.forgejo/scripts

jobs:
  build:
    runs-on: ubuntu-go
    steps:
      - name: Set Version
        run: |
          VERSION=$(date +%Y%m%d-%H%M%S)
          echo "SITE_VERSION=$VERSION" >> $FORGEJO_ENV
          echo "$VERSION"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_RUNNER_TOKEN }}

      - name: Install Hugo (extended)
        run: |
          curl -fsSL -o hugo.deb \
            "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
          sudo dpkg -i hugo.deb
          hugo version

      - name: Cache theme
        id: cache-theme
        uses: actions/cache@v4
        with:
          key: build-${{ env.HUGO_VERSION }}-${{ hashFiles('.forgejo/scripts/clone-theme.sh') }}
          path: ${{ env.BUILD_DIR }}

      - name: Clone theme
        if: steps.cache-theme.outputs.cache-hit != 'true'
        run: ${SCRIPTS_DIR}/clone-theme.sh

      - name: Copy theme customizations
        run: cp -r ${HUGO_DIR}/. ${BUILD_DIR}/

      - name: Build content
        run: ${SCRIPTS_DIR}/build-content.sh

      - name: Build
        run: |
          hugo \
            --cleanDestinationDir \
            --destination "${BUILD_DIR}/public" \
            --gc \
            --minify \
            --source "${BUILD_DIR}"

      - name: Package
        run: zip -r "${SITE_VERSION}-site.zip" "${BUILD_DIR}/public"

      - name: Upload
        run: |
          FILE_NAME="${SITE_VERSION}-site.zip"
          curl --fail \
            -H "Authorization: token ${{ secrets.ACTION_RUNNER_TOKEN }}" \
            --upload-file "$FILE_NAME" \
            "https://git.goldman.id/api/packages/${{ github.repository_owner }}/generic/web/${SITE_VERSION}/$FILE_NAME"

      - name: Push Tag
        run: |
          git config user.name "forgejo-actions-bot"
          git config user.email "actions@noreply.forgejo"
          git tag --force "${SITE_VERSION}"
          git push origin "${SITE_VERSION}" --force
