name: Build and Package

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  QUARTZ_VERSION: v4.5.2
  QUARTZ_DIR: .quartz-build

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_RUNNER_TOKEN }}

      - name: Cache Setup Quartz
        id: cache-quartz
        uses: actions/cache@v4
        with:
          path: ${{ env.QUARTZ_DIR }}
          key: quartz-${{ env.QUARTZ_VERSION }}

      - name: Setup Quartz
        if: steps.cache-quartz.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${QUARTZ_DIR}
          git config --global advice.detachedHead false
          git clone --depth=1 --branch ${QUARTZ_VERSION} https://github.com/jackyzha0/quartz.git ${QUARTZ_DIR}
          cd ${QUARTZ_DIR} && npm ci

      - name: Copy Custom Files
        run: |
          # Copy any custom files needed for the build
          cp -r .forgejo/quartz/* ${QUARTZ_DIR}/

      - name: Set version
        id: v
        run: echo "value=$(date -u +%Y.%m.%d)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and Package
        env:
          VERSION: ${{ steps.v.outputs.value }}
        run: |
          cd ${QUARTZ_DIR}
          npx quartz build --directory ../ --output public
          zip -r site-${VERSION}.zip public

      - name: Upload Package
        env:
          VERSION: ${{ steps.v.outputs.value }}
        run: |
          curl --fail \
            -H "Authorization: token ${{ secrets.ACTION_RUNNER_TOKEN }}" \
            --upload-file ${QUARTZ_DIR}/site-${VERSION}.zip \
            "https://git.goldman.id/api/packages/${{ github.repository_owner }}/generic/web/${VERSION}/site-${VERSION}.zip"

      # - name: Force push tag
      #   run: |
      #     # 1. Identify the user for the commit/tag
      #     git config user.name "forgejo-actions[bot]"
      #     git config user.email "actions@noreply.forgejo"

      #     # 2. Create or update the tag locally to point to current commit
      #     git tag -f v1.0.0

      #     # 3. Force push to the remote
      #     git push origin v1.0.0 --force
