name: Build and Package

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  QUARTZ_VERSION: v4.5.2
  QUARTZ_DIR: .quartz-build

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_RUNNER_TOKEN }}

      - name: Cache Setup Quartz
        id: cache-quartz
        uses: actions/cache@v4
        with:
          path: ${{ env.QUARTZ_DIR }}
          key: quartz-${{ env.QUARTZ_VERSION }}

      - name: Setup Quartz
        if: steps.cache-quartz.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${QUARTZ_DIR}
          git config --global advice.detachedHead false
          git clone --depth=1 --branch ${QUARTZ_VERSION} https://github.com/jackyzha0/quartz.git ${QUARTZ_DIR}
          cd ${QUARTZ_DIR} && npm ci

      - name: Copy Custom Files
        run: |
          # Copy any custom files needed for the build
          cp -r .forgejo/quartz/* ${QUARTZ_DIR}/
          # cp ~/Documents/web/.forgejo/quartz/* . && npx quartz build --directory ../web --serve

      - name: Set version
        id: v
        run: echo "value=$(date -u +%Y.%m.%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build and Package
        env:
          VERSION: ${{ steps.v.outputs.value }}
        run: |
          cd ${QUARTZ_DIR}
          npx quartz build --directory ../ --output public
          zip -r ${VERSION}.zip public

      - name: Upload Package
        env:
          VERSION: ${{ steps.v.outputs.value }}
          FILE_NAME: ${VERSION}-site.zip
        run: |
          curl --fail \
            -H "Authorization: token ${{ secrets.ACTION_RUNNER_TOKEN }}" \
            --upload-file ${QUARTZ_DIR}/${FILE_NAME} \
            "https://git.goldman.id/api/packages/${{ github.repository_owner }}/generic/web/${VERSION}/${FILE_NAME}"
          rm -frv ${QUARTZ_DIR}/${FILE_NAME}

      - name: Force push tag
        env:
          VERSION: ${{ steps.v.outputs.value }}
        run: |
          git config user.name "forgejo-actions-bot"
          git config user.email "actions@noreply.forgejo"

          git tag --force ${VERSION}
          git push origin ${VERSION} --force
