name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ci
    if: ${{ forgejo.event.workflow_run.conclusion == 'success' }}

    steps:
      - run: echo "Deploying to production..."
    # steps:
    #   - name: Download artifact
    #     uses: forgejo/download-artifact@v4
    #     with:
    #       name: site
    #       path: ./public
    #       run-id: ${{ forgejo.event.workflow_run.id }}

    #   - name: Deploy to Cloudflare Pages
    #     env:
    #       CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    #       CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
    #     run: npx wrangler@latest pages deploy ./public --project-name=idan-goldman-work
    #       --branch=main
