name: Publish

on:
  push:
    tags:
      - "*"

env:
  REGISTRY_OWNER: ${{ github.repository_owner }}
  PACKAGE_NAME: web

jobs:
  publish:
    runs-on: ubuntu
    steps:
      - name: Resolve version and file name
        run: |
          FILE_NAME="$FORGEJO_REF_NAME-site.zip"
          REPO_NAME="${FORGEJO_REPOSITORY#*/}"
          SITE_VERSION=$FORGEJO_REF_NAME

          echo "FILE_NAME=$FILE_NAME" >> "$FORGEJO_ENV"
          echo "REPO_NAME=$REPO_NAME" >> "$FORGEJO_ENV"
          echo "SITE_VERSION=$SITE_VERSION" >> "$FORGEJO_ENV"

          echo "$FILE_NAME"

      - name: Download
        run: |
          curl --fail --location \
            -H "Authorization: token ${{ secrets.FJ_ACTION_RUNNER_TOKEN }}" \
            -o "$FILE_NAME" \
            "$FORGEJO_SERVER_URL/api/packages/${FORGEJO_REPOSITORY_OWNER}/generic/${REPO_NAME}/${SITE_VERSION}/${FILE_NAME}"

      - name: Unpack
        run: |
          unzip -q "$FILE_NAME"
          test -f public/index.html

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy public --project-name=${{ env.REPO_NAME }}
